// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLaxhO58U8NDIr8UXS2LUgBSlPEMwF1Ao',
    appId: '1:282704748251:web:d3b76b4ebfe239bfe776fe',
    messagingSenderId: '282704748251',
    projectId: 'advapp-67ffc',
    authDomain: 'advapp-67ffc.firebaseapp.com',
    storageBucket: 'advapp-67ffc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVy9lf_OWOKWwK5_IanV-iyFcoea2s-V0',
    appId: '1:282704748251:android:042feb26896cdd6fe776fe',
    messagingSenderId: '282704748251',
    projectId: 'advapp-67ffc',
    storageBucket: 'advapp-67ffc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7H_TYegjLFpv_Ty9nNVn0bMmpGdS6Ymw',
    appId: '1:282704748251:ios:85f2be413ca03356e776fe',
    messagingSenderId: '282704748251',
    projectId: 'advapp-67ffc',
    storageBucket: 'advapp-67ffc.appspot.com',
    iosBundleId: 'com.example.advapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLaxhO58U8NDIr8UXS2LUgBSlPEMwF1Ao',
    appId: '1:282704748251:web:84616eea2c6c1ab3e776fe',
    messagingSenderId: '282704748251',
    projectId: 'advapp-67ffc',
    authDomain: 'advapp-67ffc.firebaseapp.com',
    storageBucket: 'advapp-67ffc.appspot.com',
  );
}
